### ISSUE TITLE
Impossible to use radio field

### ISSUE THREAD

**Issue by iamvanja** [bradwestfall/informative#10]
Consider this

```js
<Form
  onSubmit={this.handleSubmit}
  render={(formProps, formState) => {
    return (
      <form {...formProps}>
        <Field
          name='color'
          component='input'
          type='radio'
          value='yellow'
          checked
        />
        <Field
          name='color'
          component='input'
          type='radio'
          value='blue'
        />

        <Button type='submit'>
          Save
        </Button>
      </form>
    )}
  } />
```

When clicking on either of the radio inputs, error is `Uncaught TypeError: fieldValueFormatter is not a function`

The error happens on [L136](https://github.com/bradwestfall/informative/blob/master/src/Form.js#L136) (Form.js) because `this.state.fields[name]` does not have `format` and `trim` properties (L120 and L121). 
I've noticed this in the past, but always attributed it to the error on my end where I would have multiple elements with the same `name`. Radios however have to have the same name.

Please let me know if I am doing something wrong.

**Comment by bradwestfall** [comment]
Thanks @iamvanja, I just fixed this and released 0.6.2. Thanks for the find

**Comment by iamvanja** [comment]
Thanks for the quick fix. Looking at your commit, does this fix now assume that any field (non-radio) with duplicate name is part of the radio?

**Comment by bradwestfall** [comment]
It's always been assumed that any field with the same name as a previous field is a radio group. It was the same before this change. It's stated in the docs that one can only use the same name twice for radio, so I suppose weird things might happen if they went against this. I don't think it's really doable to somehow check to see if someone uses the same name when not in a radio group for the purpose of warnings

All that aside, I really don't like how radio groups are implemented internally. I want to re-write it later -- maybe when I do a new internal rewrite when I move it to the new context api
