### ISSUE TITLE
Error data from server when onSubmit promise rejected

### ISSUE THREAD

**Issue by emckay** [bradwestfall/informative#7]
Hey @bradwestfall thanks for all the work you've done on this!

Is there a built in way to handle server-side errors when the onSubmit promise is rejected?

It would be nice to be able to reject the promise with the same type of object returned by `validate` and then access those errors somewhere in `fieldState`/`formState` when I render my `Field`.

This is how redux-form handles it: http://redux-form.com/6.0.0-rc.1/examples/submitValidation/

I don't see anything like this on the README, but it's possible I was looking for the wrong term.

**Comment by bradwestfall** [comment]
Hey @emckay, thanks!

The API doesn't have any opinions on error messages, only form state. So I usually handle the promise's reject or success before I send it into the API:

```jsx
const api = {
  auth: {
    login() {
      return Promise.reject('error')
    }
  }
}

class LoginForm extends React.Component {

  onSubmit(values, formState) {
    return api.auth.login()
      .then(res => {
        console.log(res)
        return res
      })
      .catch(err => {
        console.log(err)
      })
  }

  render() {
    return (
      <Form onSubmit={this.onSubmit}>
        <Field name="email" component="input" type="email" /><br />
        <Field name="password" component="input" type="password" /><br />
        <button type="submit">Submit</button>
      </Form>
    )
  }
}
```

The return of a rejected promise into the API (after you handle it for messages the way you want) just sets the form's state to be this: https://github.com/bradwestfall/informative/blob/master/src/Form.js#L200

**Comment by emckay** [comment]
Sorry, I may not be understanding this correctly. In your example, what would you put in the `catch` in the `onSubmit` so that you can show errors on the form? It seems like you'd have to add the error messages to the state on `LoginForm` and then pass them down as props to the `Field` components.

I'm proposing that informative could handle the "submitError" state for you, in the same way that [redux-form does](http://redux-form.com/6.0.0-rc.1/examples/submitValidation/). I would consider the `submitErrors` to be part of the form's state, especially given that there is already a `formState` variable called `submitFailed`. `submitErrors` would just contain information about why the submit failed, in the same way that `formState.errors` contains data about why the fields are invalid.

Here's a very rough draft of a patch that might make my feature request more clear: https://github.com/bradwestfall/informative/compare/master...emckay:submit-errors . This patch is similar but slightly different from the way redux-form works, as my patch does not merge the validation errors and the submit errors.

This patch lets me do something like this in my `FieldWrap`:

```jsx
const FieldWrap = (props) => {
  const { label,  ...rest } = props
  return (
    <Field
      {...rest}
      render={(events, fieldState) => {
        return (
          <FormGroup>
            <Label>{label}</Label>
            <Input {...rest} {...events}>{children}</Input>
            <FormFeedback>{fieldState.submitError}</FormFeedback>
          </FormGroup>
        )
      }}
    />
  )
}
```

**Comment by bradwestfall** [comment]
@emckay I did not understand your original question, I think I do now. So right now the API does not allow you to take network responses like the error from submission and plug them into the form's state for the purposes of each field wrap having access to it. So the solution I posted originally is good for a general message, but not a field-by-field message which is what I think you want. 

I'll have to consider the best way to do this, I'll take into account the example changes you posted. Give me a few days to ponder. And thanks for helping out :)

**Comment by emckay** [comment]
No worries! My example patch is extremely rough, so feel free to disregard it entirely. It seems to be working for me in a very small project, but I didn't spend a ton of time figuring out the "best way" to do it in your code.

I can understand putting this off for awhile because I think any approach will have to make some strong decisions about when to clear the submit errors and how to merge them (if at all) with the synchronous validation errors in a way that doesn't surprise developers using this package.

**Comment by bradwestfall** [comment]
@emckay I was thinking, and it might not make sense to plug outside state into informative this way. But you can pass anything you want into your own FieldWrap. So since the network stuff is handled outside of informative, why not handle submission errors by simply passing them directly into your FieldWrap instead of into the API and expecting them to end up somewhere in `formState`? I made a working example https://codesandbox.io/s/pYVE8JXJp

So the idea is that if you type into the fields, they will be invalid from a front-end validation perspective (until you type a valid email and password of at least 6 chars). Then when you do the submission and it fails, pass the failed messages into each `<FieldWrap>`. Then the field wrap can decide what to do with two styles of error messages (front-end and backend)

**Comment by emckay** [comment]
Yeah it's definitely something you could leave up to the user. However, this is a common enough pattern for me that it would be something I would write an HOC for if it was not in the library. 

There is some precedent for including server validation errors by redux-form, and like I said before, `formState` already has a `submitFailed` boolean, so this doesn't seem like too much of a stretch.

Totally understand that you have to draw the line somewhere though, and it might make sense to add this later on in the development cycle since it has to have some relatively strong opinions about how to merge and clear the errors.

**Comment by bradwestfall** [comment]
Yea, the more I've thought about this, the more I think I should not integrate the network errors into the API. I think it muddies up the API's internal notion of errors which are coming from real-time front-end errors. I think the scenario you've laid out is better solved by the user. I myself use an application-level abstraction for forms where I implement a component called `<CommonForm>` which in turn implements `informative` `<Form>`. My common-form does HoC's for thinks like notices and handling network responses.

**Comment by emckay** [comment]
Makes sense. Thanks for talking through this with me!
